spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        person-topic-in:
          destination: person-topic
          contentType: application/json
          group: allIntegrationGroupId
        employee-topic-out:
          destination: employee-topic
          contentType: application/json